#!/usr/bin/env bash
#
# churn_cli.sh — the OPTIONAL Bolt-over-UDS wire demonstration of the IoT ingest + retention churn.
#
# This boots a real `graphus-server` and drives the same time-series workload — insert a batch of new
# `:Reading`s per tick, then `DETACH DELETE` the readings aged out of the retention window — over a
# Unix Domain Socket with the real `graphus-cli` (Bolt + PackStream, no in-process shortcuts). It
# asserts the live `:Reading` count reaches and holds the steady state around the window.
#
# It deliberately does NOT attempt to prove the storage plateau: Graphus's MVCC garbage collection is
# a maintenance operation with no wire-reachable trigger (see ../README.md → "Transport"), so over the
# wire the delete only tombstones and the footprint would grow. The reclamation plateau is proven by
# the in-process `iot_churn` driver; this script's job is to show the ingest+retention churn works
# over the real wire and reaches a steady live count.
#
# Invoked by ../run.sh (which passes the server + cli binary paths). Standalone usage:
#   data/churn_cli.sh <graphus-server> <graphus-cli> [ticks] [rate] [window] [sensors]

set -euo pipefail

SERVER_BIN="${1:?usage: churn_cli.sh <server> <cli> [ticks] [rate] [window] [sensors]}"
CLI_BIN="${2:?usage: churn_cli.sh <server> <cli> [ticks] [rate] [window] [sensors]}"
TICKS="${3:-12}"
RATE="${4:-20}"
WINDOW="${5:-60}"
SENSORS="${6:-4}"

if [ -t 1 ]; then
  GREEN=$'\e[32m'; RED=$'\e[31m'; DIM=$'\e[2m'; RESET=$'\e[0m'
else
  GREEN=''; RED=''; DIM=''; RESET=''
fi

WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/graphus-iot-wire-XXXXXX")"
CONFIG="$WORKDIR/graphus.toml"
SOCKET="$WORKDIR/graphus.sock"
SERVER_LOG="$WORKDIR/server.log"
ADMIN_USER="iot"
ADMIN_PW="iot-timeseries-demo-uds-pw-1"

SERVER_PID=""
cleanup() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill -TERM "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -rf "$WORKDIR"
}
trap cleanup EXIT INT TERM

# A UDS-only config; admin bound to this uid so the SO_PEERCRED gate admits our own connections.
cat > "$CONFIG" <<EOF
# Generated by examples/iot-timeseries/data/churn_cli.sh — a UDS-only IoT churn demo.
store_path = "$WORKDIR/data"
buffer_pool_pages = 2048
uds_path = "$SOCKET"
rest_addr = ""
jwt_secret = "graphus-iot-timeseries-demo-uds-only-secret-32+"

[auth]
admin_user = "$ADMIN_USER"
admin_password = "$ADMIN_PW"
admin_uid = $(id -u)
EOF

"$SERVER_BIN" "$CONFIG" >>"$SERVER_LOG" 2>&1 &
SERVER_PID=$!
# Wait for the UDS to be bound, or fail fast if the server died.
ready=0
for _ in $(seq 1 100); do
  if [ -S "$SOCKET" ]; then ready=1; break; fi
  if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "${RED}server exited during startup; last log lines:${RESET}" >&2
    tail -n 15 "$SERVER_LOG" >&2
    exit 1
  fi
  sleep 0.1
done
[ "$ready" = "1" ] || { echo "${RED}server did not bind UDS $SOCKET${RESET}" >&2; tail -n 15 "$SERVER_LOG" >&2; exit 1; }

# cypher <stmt> — run one statement over the UDS with the real CLI.
cypher() { GRAPHUS_PASSWORD="$ADMIN_PW" "$CLI_BIN" --uds "$SOCKET" --user "$ADMIN_USER" -c "$1"; }
# scalar <stmt> — run a single-cell query and print just the value (strip table formatting).
scalar() {
  cypher "$1" | awk -F'|' '
    /^\|/ { rows++; if (rows == 2) { v = $2; gsub(/^[ \t"]+|[ \t"]+$/, "", v); print v } }'
}

echo "${DIM}wire demo: server pid $SERVER_PID on $SOCKET — ticks=$TICKS rate=$RATE window=$WINDOW sensors=$SENSORS${RESET}"

# Sensor fleet (created once).
for i in $(seq 0 $((SENSORS - 1))); do
  cypher "CREATE (:Sensor {id: 's-$i', kind: 'temperature', site: $((i % 4))})" >/dev/null
done

# Churn loop: insert RATE readings per tick, then delete readings aged out of the window.
seq_no=0
for t in $(seq 0 $((TICKS - 1))); do
  for _ in $(seq 1 "$RATE"); do
    sensor=$((seq_no % SENSORS))
    cypher "MATCH (s:Sensor {id: 's-$sensor'}) CREATE (s)-[:EMITTED]->(:Reading {seq: $seq_no, value: $((seq_no % 1000))})" >/dev/null
    seq_no=$((seq_no + 1))
  done
  if [ "$seq_no" -gt "$WINDOW" ]; then
    cutoff=$((seq_no - WINDOW))
    cypher "MATCH (r:Reading) WHERE r.seq < $cutoff DETACH DELETE r" >/dev/null
  fi
done

# Assert the steady-state live count is within the band [window, window+rate).
live="$(scalar "MATCH (r:Reading) RETURN count(r) AS c")"
lo="$WINDOW"
hi=$((WINDOW + RATE))
if [ "${live:-0}" -ge "$lo" ] && [ "${live:-0}" -lt "$hi" ]; then
  echo "  ${GREEN}✓${RESET} wire ingest+retention reached steady state: live=$live in [$lo, $hi)"
  echo "GRAPHUS_IOT_WIRE_OK"
  exit 0
else
  echo "  ${RED}✗${RESET} wire steady-state live count $live outside [$lo, $hi)"
  exit 1
fi
