#!/usr/bin/env bash
#
# Graphus MVP end-to-end demonstration — a social network over a Unix Domain Socket (Bolt/UDS).
#
# This script doubles as an executable E2E test: it drives the REAL `graphus-server` and
# `graphus-cli` binaries (no in-process shortcuts) over a UDS, asserts every expected result, and
# exits non-zero the moment any assertion fails. Its goal is to prove, empirically, that Graphus is
# already usable as a Minimum Viable Product:
#
#   1. The server accepts connections over UDS (kernel-protected, peer-cred + password auth).
#   2. Nodes and relationships can be inserted (the classic social-network model).
#   3. The data and the server survive a restart — proven twice over:
#        * a GRACEFUL restart (SIGTERM → clean shutdown → reboot from the same store);
#        * a CRASH + RECOVERY (SIGKILL mid-life → reboot → WAL replay restores committed state).
#   4. The server can search and manipulate data (friend-of-friend recommendations, aggregation,
#      SET / DELETE / MERGE), and those mutations are themselves durable across the crash.
#
# Usage:
#   examples/social-network-uds/run.sh            # builds the binaries if needed, then runs
#   GRAPHUS_BIN_DIR=target/release run.sh         # use pre-built binaries from a custom dir
#
# Requirements: a Unix host (Linux/macOS), bash, and a checkout that builds. The script is fully
# self-contained: it creates its own temp store, config, and socket, and removes them on exit.

set -euo pipefail

# --------------------------------------------------------------------------------------------------
# Pretty output helpers
# --------------------------------------------------------------------------------------------------
if [ -t 1 ]; then
  BOLD=$'\e[1m'; GREEN=$'\e[32m'; RED=$'\e[31m'; BLUE=$'\e[34m'; DIM=$'\e[2m'; RESET=$'\e[0m'
else
  BOLD=''; GREEN=''; RED=''; BLUE=''; DIM=''; RESET=''
fi

CHECKS=0
FAILURES=0

section() { printf '\n%s== %s ==%s\n' "$BOLD$BLUE" "$1" "$RESET"; }
info()    { printf '%s· %s%s\n' "$DIM" "$1" "$RESET"; }

# assert <description> <expected> <actual>
assert() {
  CHECKS=$((CHECKS + 1))
  if [ "$2" = "$3" ]; then
    printf '  %s✓%s %s %s(= %s)%s\n' "$GREEN" "$RESET" "$1" "$DIM" "$3" "$RESET"
  else
    FAILURES=$((FAILURES + 1))
    printf '  %s✗ %s%s — expected %s[%s]%s, got %s[%s]%s\n' \
      "$RED" "$1" "$RESET" "$BOLD" "$2" "$RESET" "$BOLD" "$3" "$RESET"
  fi
}

# --------------------------------------------------------------------------------------------------
# Locate (or build) the binaries
# --------------------------------------------------------------------------------------------------
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BIN_DIR="${GRAPHUS_BIN_DIR:-$REPO_ROOT/target/release}"
SERVER="$BIN_DIR/graphus-server"
CLI="$BIN_DIR/graphus-cli"

if [ ! -x "$SERVER" ] || [ ! -x "$CLI" ]; then
  section "Building graphus-server and graphus-cli (release)"
  ( cd "$REPO_ROOT" && cargo build --release -p graphus-server -p graphus-cli )
fi
[ -x "$SERVER" ] || { echo "${RED}fatal: server binary not found at $SERVER${RESET}" >&2; exit 2; }
[ -x "$CLI" ]    || { echo "${RED}fatal: cli binary not found at $CLI${RESET}" >&2; exit 2; }

# --------------------------------------------------------------------------------------------------
# Workspace: a private temp store + config + socket, removed on exit
# --------------------------------------------------------------------------------------------------
WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/graphus-mvp-XXXXXX")"
CONFIG="$WORKDIR/graphus.toml"
SOCKET="$WORKDIR/graphus.sock"
SERVER_LOG="$WORKDIR/server.log"
ADMIN_USER="alice"
ADMIN_PW="social-demo-pw-1"

# Evidence collection (rmp #249): the standardized report.json + report.md land in this example's
# git-ignored evidence/ dir. The on-disk store device + WAL live under $WORKDIR/data (default DB).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EVIDENCE_DIR="$SCRIPT_DIR/evidence"
STORE_FILE="$WORKDIR/data/graphus.store"
WAL_FILE="$WORKDIR/data/graphus.wal"
PEAK_RSS_BYTES=0          # high-watermark of the server's RSS, sampled at the heavy phases
SERVER_START_EPOCH=0      # wall-clock epoch (s) of the most recent server boot, for uptime

SERVER_PID=""
cleanup() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill -TERM "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -rf "$WORKDIR"
}
trap cleanup EXIT INT TERM

# A UDS-only configuration. No network listener is enabled, so no TLS material is needed; the JWT
# secret is set only because the security catalog mandates a >=32-byte secret even when unused. The
# admin user is bound to this process's uid so the UDS SO_PEERCRED gate admits our own connections.
cat > "$CONFIG" <<EOF
# Generated by examples/social-network-uds/run.sh — a UDS-only MVP demo configuration.
store_path = "$WORKDIR/data"
buffer_pool_pages = 2048
uds_path = "$SOCKET"
rest_addr = ""
jwt_secret = "graphus-mvp-social-demo-uds-only-secret-32+"

[auth]
admin_user = "$ADMIN_USER"
admin_password = "$ADMIN_PW"
admin_uid = $(id -u)
EOF

# --------------------------------------------------------------------------------------------------
# Server lifecycle helpers
# --------------------------------------------------------------------------------------------------
start_server() {
  "$SERVER" "$CONFIG" >>"$SERVER_LOG" 2>&1 &
  SERVER_PID=$!
  SERVER_START_EPOCH="$(date +%s)"
  # Wait for the UDS to be bound (readiness), or fail fast if the process died.
  for _ in $(seq 1 100); do
    if [ -S "$SOCKET" ]; then return 0; fi
    if ! kill -0 "$SERVER_PID" 2>/dev/null; then
      echo "${RED}server exited during startup; last log lines:${RESET}" >&2
      tail -n 15 "$SERVER_LOG" >&2
      exit 1
    fi
    sleep 0.1
  done
  echo "${RED}server did not bind UDS $SOCKET within timeout${RESET}" >&2
  tail -n 15 "$SERVER_LOG" >&2
  exit 1
}

stop_server_graceful() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill -TERM "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  SERVER_PID=""
}

# Simulate a power failure / crash: SIGKILL leaves the process no chance to flush or shut down
# cleanly. Recovery must therefore rely entirely on the durable WAL + store.
crash_server() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill -KILL "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -f "$SOCKET" # the kernel does not unlink the socket file on SIGKILL
  SERVER_PID=""
}

# --------------------------------------------------------------------------------------------------
# Evidence helpers (rmp #249) — portable RSS sampling of the LIVE server process
# --------------------------------------------------------------------------------------------------
# _now_ms — current time in milliseconds (GNU date), or seconds*1000 fallback (macOS BSD date).
_now_ms() {
  local ns
  ns="$(date +%s%N 2>/dev/null)"
  case "$ns" in
    *N|'') echo "$(( $(date +%s) * 1000 ))" ;; # %N unsupported → second resolution
    *)     echo "$(( ns / 1000000 ))" ;;
  esac
}

# server_rss_bytes <pid> — current resident set size of the server in bytes (Linux /proc, macOS ps).
server_rss_bytes() {
  local pid="$1" bytes=0
  if [ -r "/proc/$pid/statm" ]; then
    # /proc/<pid>/statm: "size resident ..." in pages; resident is field 2.
    local pages page_sz
    pages="$(awk '{print $2}' "/proc/$pid/statm" 2>/dev/null || echo 0)"
    page_sz="$(getconf PAGE_SIZE 2>/dev/null || echo 4096)"
    bytes=$(( ${pages:-0} * ${page_sz:-4096} ))
  elif command -v ps >/dev/null 2>&1; then
    # macOS / other Unix: ps reports RSS in KiB (headerless via "=").
    local kib
    kib="$(ps -o rss= -p "$pid" 2>/dev/null | tr -d ' ' || echo 0)"
    bytes=$(( ${kib:-0} * 1024 ))
  fi
  echo "${bytes:-0}"
}

# sample_peak_rss — read the live server's RSS once and keep the running high-watermark.
sample_peak_rss() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    local rss
    rss="$(server_rss_bytes "$SERVER_PID")"
    if [ "${rss:-0}" -gt "$PEAK_RSS_BYTES" ]; then
      PEAK_RSS_BYTES="$rss"
    fi
  fi
}

# Run a Cypher statement and print the raw rendered table.
cypher() {
  GRAPHUS_PASSWORD="$ADMIN_PW" "$CLI" --uds "$SOCKET" --user "$ADMIN_USER" -c "$1"
}

# Run a statement that returns exactly one column in one row, and print just that scalar value
# (table formatting and surrounding quotes stripped). Used by assertions.
scalar() {
  cypher "$1" | awk -F'|' '
    /^\|/ { rows++; if (rows == 2) { v = $2; gsub(/^[ \t"]+|[ \t"]+$/, "", v); print v } }
  '
}

# ==================================================================================================
# PHASE 1 — Boot the server and accept a UDS connection
# ==================================================================================================
section "Phase 1 — Boot Graphus and connect over UDS"
start_server
info "server pid $SERVER_PID listening on $SOCKET"
assert "server answers a trivial query over UDS" "1" "$(scalar "RETURN 1 AS one")"
assert "graph starts empty" "0" "$(scalar "MATCH (n) RETURN count(n) AS c")"

# ==================================================================================================
# PHASE 2 — Build the social network (insert nodes and relationships)
# ==================================================================================================
section "Phase 2 — Insert the social graph (people, friendships, follows, posts)"

# People. FRIEND is modelled as a mutual relationship: we create it once per pair and query it
# undirected. FOLLOWS is directional (a one-way subscription). POSTED links a person to a Post.
# Time the bulk-insert phase so the evidence report can derive its throughput (ops/sec).
INSERT_START_MS="$(_now_ms)"
cypher "
CREATE (alice:Person {name:'Alice', age:30, city:'Lisbon'}),
       (bob:Person   {name:'Bob',   age:34, city:'Porto'}),
       (carol:Person {name:'Carol', age:28, city:'Lisbon'}),
       (dave:Person  {name:'Dave',  age:41, city:'Braga'}),
       (eve:Person   {name:'Eve',   age:25, city:'Lisbon'}),
       (frank:Person {name:'Frank', age:37, city:'Porto'}),
       (alice)-[:FRIEND {since:2015}]->(bob),
       (alice)-[:FRIEND {since:2018}]->(carol),
       (bob)-[:FRIEND {since:2016}]->(dave),
       (carol)-[:FRIEND {since:2020}]->(eve),
       (dave)-[:FRIEND {since:2019}]->(frank),
       (alice)-[:FOLLOWS]->(frank),
       (bob)-[:FOLLOWS]->(frank),
       (carol)-[:FOLLOWS]->(frank),
       (eve)-[:FOLLOWS]->(alice),
       (alice)-[:POSTED]->(:Post {text:'Hello graph world', likes:12}),
       (bob)-[:POSTED]->(:Post {text:'Bolt over UDS is fast', likes:7})
RETURN count(*) AS created" > /dev/null
INSERT_MS=$(( $(_now_ms) - INSERT_START_MS ))
info "bulk insert took ${INSERT_MS} ms"
sample_peak_rss   # the insert is the write-heavy phase; capture the server's RSS here

assert "six people created"        "6" "$(scalar "MATCH (p:Person) RETURN count(p) AS c")"
assert "five friendships created"  "5" "$(scalar "MATCH ()-[r:FRIEND]->() RETURN count(r) AS c")"
assert "four follows created"      "4" "$(scalar "MATCH ()-[r:FOLLOWS]->() RETURN count(r) AS c")"
assert "two posts created"         "2" "$(scalar "MATCH (:Post) RETURN count(*) AS c")"

# ==================================================================================================
# PHASE 3 — Search the graph
# ==================================================================================================
section "Phase 3 — Search and traverse"

info "Alice's direct friends:"
cypher "MATCH (:Person {name:'Alice'})-[:FRIEND]-(f) RETURN f.name AS friend ORDER BY friend"
assert "Alice has two direct friends" "2" \
  "$(scalar "MATCH (:Person {name:'Alice'})-[:FRIEND]-(f) RETURN count(DISTINCT f) AS c")"

info "Friend-of-friend recommendations for Alice (not already her friends, not herself):"
cypher "
MATCH (me:Person {name:'Alice'})-[:FRIEND]-(:Person)-[:FRIEND]-(fof:Person)
WHERE fof <> me AND NOT (me)-[:FRIEND]-(fof)
RETURN DISTINCT fof.name AS recommendation ORDER BY recommendation"
# Alice—Bob—Dave and Alice—Carol—Eve ⇒ {Dave, Eve}
assert "Alice gets two FoF recommendations" "2" \
  "$(scalar "MATCH (me:Person {name:'Alice'})-[:FRIEND]-(:Person)-[:FRIEND]-(fof:Person)
             WHERE fof <> me AND NOT (me)-[:FRIEND]-(fof)
             RETURN count(DISTINCT fof) AS c")"

info "Most-followed person:"
cypher "
MATCH (p:Person)<-[:FOLLOWS]-(follower)
RETURN p.name AS person, count(follower) AS followers
ORDER BY followers DESC, person ASC LIMIT 3"
assert "Frank is the most followed (3 followers)" "Frank" \
  "$(scalar "MATCH (p:Person)<-[:FOLLOWS]-(f)
             WITH p, count(f) AS followers
             RETURN p.name AS person ORDER BY followers DESC, person ASC LIMIT 1")"

assert "three people live in Lisbon" "3" \
  "$(scalar "MATCH (p:Person {city:'Lisbon'}) RETURN count(p) AS c")"

# Record the totals we expect to survive the restarts.
NODES_BEFORE="$(scalar "MATCH (n) RETURN count(n) AS c")"
RELS_BEFORE="$(scalar "MATCH ()-[r]->() RETURN count(r) AS c")"
info "totals before restart: $NODES_BEFORE nodes, $RELS_BEFORE relationships"

# ==================================================================================================
# PHASE 4 — Graceful restart: the data survives a clean shutdown + reboot
# ==================================================================================================
section "Phase 4 — Graceful restart (SIGTERM → reboot from the same store)"
stop_server_graceful
info "server stopped cleanly; socket gone: $([ -S "$SOCKET" ] && echo no || echo yes)"
start_server
info "server rebooted (pid $SERVER_PID) from $WORKDIR/data"

assert "node count survived graceful restart" "$NODES_BEFORE" "$(scalar "MATCH (n) RETURN count(n) AS c")"
assert "relationship count survived graceful restart" "$RELS_BEFORE" "$(scalar "MATCH ()-[r]->() RETURN count(r) AS c")"
assert "a specific node survived (Alice in Lisbon)" "Lisbon" \
  "$(scalar "MATCH (p:Person {name:'Alice'}) RETURN p.city AS city")"
assert "a relationship property survived (Alice–Bob friends since)" "2015" \
  "$(scalar "MATCH (:Person {name:'Alice'})-[r:FRIEND]-(:Person {name:'Bob'}) RETURN r.since AS since")"

# ==================================================================================================
# PHASE 5 — Manipulate the data, then prove it is durable across a CRASH
# ==================================================================================================
section "Phase 5 — Manipulate data (SET / MERGE / DELETE)"

info "Alice moves to Madrid:"
cypher "MATCH (p:Person {name:'Alice'}) SET p.city = 'Madrid' RETURN p.city AS city" > /dev/null
assert "Alice's city updated" "Madrid" "$(scalar "MATCH (p:Person {name:'Alice'}) RETURN p.city AS city")"

info "Alice and Eve become friends (new relationship):"
cypher "
MATCH (a:Person {name:'Alice'}), (e:Person {name:'Eve'})
MERGE (a)-[:FRIEND {since:2026}]->(e)
RETURN 1 AS ok" > /dev/null
assert "friendship count is now six" "6" "$(scalar "MATCH ()-[r:FRIEND]->() RETURN count(r) AS c")"

info "Alice unfriends Bob (delete one relationship):"
cypher "MATCH (:Person {name:'Alice'})-[r:FRIEND]-(:Person {name:'Bob'}) DELETE r" > /dev/null
assert "friendship count back to five" "5" "$(scalar "MATCH ()-[r:FRIEND]->() RETURN count(r) AS c")"
assert "Alice and Bob are no longer friends" "0" \
  "$(scalar "MATCH (:Person {name:'Alice'})-[r:FRIEND]-(:Person {name:'Bob'}) RETURN count(r) AS c")"

info "Delete Bob's post (DETACH DELETE removes the node and its edges):"
cypher "MATCH (b:Person {name:'Bob'})-[:POSTED]->(post:Post) DETACH DELETE post" > /dev/null
assert "one post remains" "1" "$(scalar "MATCH (:Post) RETURN count(*) AS c")"

NODES_AFTER_EDIT="$(scalar "MATCH (n) RETURN count(n) AS c")"
RELS_AFTER_EDIT="$(scalar "MATCH ()-[r]->() RETURN count(r) AS c")"
info "totals after manipulation: $NODES_AFTER_EDIT nodes, $RELS_AFTER_EDIT relationships"
sample_peak_rss   # capture the server's RSS after the mutation phase

# ==================================================================================================
# PHASE 6 — Crash recovery: the manipulations survive a SIGKILL (power-failure simulation)
# ==================================================================================================
section "Phase 6 — Crash + recovery (SIGKILL → reboot → WAL replay)"
crash_server
info "server KILLed (no clean shutdown). Rebooting; recovery must replay the WAL."
start_server
info "server recovered (pid $SERVER_PID)"
grep -qi "recover" "$SERVER_LOG" && info "recovery path exercised (see server.log)" || true

assert "node count survived the crash"          "$NODES_AFTER_EDIT" "$(scalar "MATCH (n) RETURN count(n) AS c")"
assert "relationship count survived the crash"  "$RELS_AFTER_EDIT"  "$(scalar "MATCH ()-[r]->() RETURN count(r) AS c")"
assert "the SET survived the crash (Alice in Madrid)" "Madrid" \
  "$(scalar "MATCH (p:Person {name:'Alice'}) RETURN p.city AS city")"
assert "the MERGE survived the crash (Alice–Eve are friends)" "1" \
  "$(scalar "MATCH (:Person {name:'Alice'})-[:FRIEND]-(:Person {name:'Eve'}) RETURN count(*) AS c")"
assert "the DELETE survived the crash (Alice–Bob still unfriended)" "0" \
  "$(scalar "MATCH (:Person {name:'Alice'})-[:FRIEND]-(:Person {name:'Bob'}) RETURN count(*) AS c")"
assert "the post deletion survived the crash" "1" "$(scalar "MATCH (:Post) RETURN count(*) AS c")"

# ==================================================================================================
# PHASE 7 — Collect standardized performance evidence (rmp #249)
# ==================================================================================================
# The server is still alive (the recovered pid), so we can read its real CPU + RSS, and the on-disk
# store/WAL footprint reflects the full workload that survived the crash. We delegate the heavy
# /proc + getrusage metering and the report emission to the dev-only `measure_server` harness binary,
# which writes report.json + report.md into the git-ignored evidence/ dir. This is purely ADDITIVE —
# it changes none of the assertions above, and a metering failure must not fail the demonstration.
section "Phase 7 — Collect performance evidence (CPU / RAM / storage)"
sample_peak_rss
SERVER_UPTIME_SECS=$(( $(date +%s) - SERVER_START_EPOCH ))
[ "$SERVER_UPTIME_SECS" -lt 1 ] && SERVER_UPTIME_SECS=1   # avoid a zero-length CPU window

# Logical sizing for the amplification ratios. The durable graph is the post-crash state
# (NODES_AFTER_EDIT nodes + RELS_AFTER_EDIT rels). We document a coarse logical-bytes estimate
# (~256 B/node + ~128 B/rel covers the fixed-record node/rel payloads and their small property
# values) so the ratios are meaningful-but-honest proxies rather than precise accounting.
LOGICAL_GRAPH_BYTES=$(( NODES_AFTER_EDIT * 256 + RELS_AFTER_EDIT * 128 ))
# The bulk insert created 8 nodes + 11 relationships = 19 write operations.
INSERT_OPS=19

MEASURE_BIN="$BIN_DIR/measure_server"
if [ ! -x "$MEASURE_BIN" ]; then
  info "building the dev-only measure_server harness binary (debug)…"
  ( cd "$REPO_ROOT" && cargo build -q -p graphus-examples-harness --bin measure_server ) || true
  MEASURE_BIN="$REPO_ROOT/target/debug/measure_server"
fi

if [ -x "$MEASURE_BIN" ] && [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
  "$MEASURE_BIN" \
    --evidence-dir "$EVIDENCE_DIR" \
    --scenario "social-network-uds" \
    --description "Social network over a Bolt/UDS connection: insert, traverse, mutate, and survive a graceful restart + a hard crash." \
    --pid "$SERVER_PID" \
    --uptime-secs "$SERVER_UPTIME_SECS" \
    --store "$STORE_FILE" \
    --wal "$WAL_FILE" \
    --nodes "$NODES_AFTER_EDIT" \
    --rels "$RELS_AFTER_EDIT" \
    --peak-rss-bytes "$PEAK_RSS_BYTES" \
    --workload-ops "$INSERT_OPS" \
    --workload-secs "$(LC_ALL=C awk "BEGIN{printf \"%.6f\", ${INSERT_MS:-0}/1000}")" \
    --logical-graph-bytes "$LOGICAL_GRAPH_BYTES" \
    --param "connection=uds-bolt" \
    --param "buffer_pool_pages=2048" \
    --param "restarts=graceful+crash" \
    --phase "bulk-insert=${INSERT_MS:-0}" \
    --note "Dataset is the durable post-crash graph; storage footprint is measured after WAL replay." \
    && info "evidence written to $EVIDENCE_DIR" \
    || info "evidence collection failed (non-fatal); see output above"
  assert "evidence report.json was produced" "yes" \
    "$([ -f "$EVIDENCE_DIR/report.json" ] && echo yes || echo no)"
  assert "evidence report.md was produced" "yes" \
    "$([ -f "$EVIDENCE_DIR/report.md" ] && echo yes || echo no)"
else
  info "measure_server unavailable or server not alive; skipping evidence collection (non-fatal)"
fi

# ==================================================================================================
# Summary
# ==================================================================================================
stop_server_graceful
section "Result"
printf '%s checks run, %s failures.\n' "$CHECKS" "$FAILURES"
if [ "$FAILURES" -eq 0 ]; then
  printf '%s%sMVP DEMONSTRATION PASSED%s — Graphus accepted UDS connections, stored a social graph,\n' "$BOLD" "$GREEN" "$RESET"
  printf 'searched and manipulated it, and preserved every committed change across a graceful\n'
  printf 'restart and a hard crash.\n'
  exit 0
else
  printf '%s%sMVP DEMONSTRATION FAILED%s — %s assertion(s) did not hold.\n' "$BOLD" "$RED" "$RESET" "$FAILURES"
  exit 1
fi
